---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-tk3
  namespace: tk3
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: tk3
  name: jupyter-instance-manager
rules:
- apiGroups: [""]
  resources: ["jupyterinstances"]
  verbs: ["get", "watch", "list", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-jupyter-instance
  namespace: tk3
subjects:
- kind: ServiceAccount
  name: webapp-tk3
roleRef:
  kind: Role
  name: jupyter-instance-manager
  apiGroup: rbac.authorization.k8s.io

