apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: 2018-07-04T13:12:22Z
    name: standard
    namespace: ""
    resourceVersion: "514"
    selfLink: /apis/storage.k8s.io/v1/storageclasses/standard
    uid: e33f6242-7f8b-11e8-bc6c-025000000001
  provisioner: docker.io/hostpath
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""